### PR TITLE
Fix #68 - Show help if run without arguments

### LINKED ISSUE #68: Show help if run without arguments
Running `bugzilla` without arguments leaves this trace:
```
➜  ~ bugzilla            
Traceback (most recent call last):
  File "/usr/bin/bugzilla", line 1117, in <module>
    main()
  File "/usr/bin/bugzilla", line 1108, in main
    raise RuntimeError("Unexpected action '%s'" % action)
RuntimeError: Unexpected action 'None'
```
I expected --help to be shown instead.

https://bugzilla.redhat.com/show_bug.cgi?id=1513819#c10

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by crobinso** [comment]
Thanks for the patch, but does the issue actually reproduce with git? It doesn't for me. If you can still reproduce please provide steps with git. Pretty sure this was fixed in this commit:

commit 3d87c290682f75ffad0657f498759526184f8a11
Author: Cole Robinson <crobinso@redhat.com>
Date:   Tue Nov 21 15:44:19 2017 -0500

    bin: Give consistent error with py3 if missing command (bz 1513819)

**Comment by abitrolly** [comment]
I can't test it if it is not released for Fedora repositories.

**Comment by abitrolly** [comment]
I can test if I can install it. I don't know how to build Fedora package to install.

**Comment by crobinso** [comment]
./setup.py rpm will build an rpm, you'll need to install rpmbuild and possibly some build dependencies.

Either way this particular issue is fixed upstream already in my testing, so I'm closing this

**Comment by abitrolly** [comment]
Where is the upstream?

**Comment by crobinso** [comment]
upstream == this git repo. But I released v2.2.0 over the weekend which should be fixed

**Comment by abitrolly** [comment]
Is it the release - https://bodhi.fedoraproject.org/updates/FEDORA-2018-8368410b1a ? I forgot how to test it - `bodhi 4.0.0` contains explanation patch, but it is still not deployed.

**Comment by crobinso** [comment]
dnf --enablerepo=updates-testing update python-bugzilla

**Comment by abitrolly** [comment]
No, doesn't work. Maybe because the update is not in testing yet. :) 

image

**Pull request closed without merging**
