### PR TITLE
Support Bugzilla API keys

### PR DESCRIPTION
**Pull request by djmitche**
Rather than encode my password in a dotfile, it would be great to use an [API key](https://bugzilla.mozilla.org/show_bug.cgi?id=893195) instead.

### CODE REVIEW

**Comment by djmitche** [comment]
@crobinso I kind of threaded API keys in there with user/password for the user side, and with tokens for the caching side.  What do you think?

**Comment by djmitche** [comment]
@crobinso any chance you could take a look?

**Comment by djmitche** [comment]
I'll update this to pass the tests...

**Comment by crobinso** [comment]
Sorry for the delay. Took a brief look. I didn't know about landfill.bugzilla.org, that's pretty useful.

Please separate the Token->TokenCache renaming stuff into its own patch, since it clogs up the functional changes a bit. After that I'll pull it down and give it a spin.

**Comment by djmitche** [comment]
OK, thanks for your patience -- I split the commits up and fixed two minor bugs the tests turned up.

**Comment by crobinso** [comment]
Thanks for the updates. I've played with it a bit now and have some thoughts.

I don't like bz.login(api_key=XXX). Right now login() is a wrapper for the bugzilla login API call; extending it to handle the api_key parameter to mean 'store this in our token cache' is pulling it in a different direction. I think for starters we should just have Bugzilla(api_key="XXX") be the code entry point for using an API key. That loses the ability to use an api_key outside of Bugzilla() init time but I don't think that's a big concern.

Storing the API key in ~/.config/python-bugzilla/tokencache doesn't really make sense to me, again it seems to be conflating two different paradigms: one is a login token acquired after an explicit login from the user, the other is a long living API password the user has to deliberately create and fetch. For automatic usage of an API key we should mandate the ~/.config/python-bugzilla/bugzillarc route, which the user either fills in manually by hand, and/or we can add a /usr/bin/bugzilla login --save-api-key option or similar, which takes the API key via getpass(), saves it in the RC file, and tells the user "API key saved to ~/.config/..."

In that vein, having a login --api-key option that takes the key on the command line isn't a good idea IMO. I know we have the --password option but that's a bad idea too. It's generally not a good idea to encourage specifying any secret keys/passwords on the command line, since it shows up in ps, bash history, etc. If we want to give an option for testing a one off API key then we should use an environment variable, but not sure how important that use case is.

So the change order should be roughly:

1) Add Bugzilla(api_key=X), make it work, add test case and example. api_key is transient and not saved to disk anywhere.
2) Add bugzillarc support for api_key
3) Consider a bugzilla login --save-api-key convenience option. This might need some rework of the bugzillarc code, to make it it's own file/API object that bin/bugzilla interacts with. That or add a convenience function like Bugzilla.save_api_key(...). Not sure, I'd need to play with it.

Another thing to investigate is how this fails when the key is wrong/revoked, I think we would want to amend the error to point to the bugzillarc file if that's where the key came from.

Thoughts?

**Comment by djmitche** [comment]
I can work on the first and second points.  It sounds like the third is a nice-to-have, a little vague, and not something I need, so I'll leave that bit.

**Comment by djmitche** [comment]
OK, updated, what do you think?  I can drop the BugzillaToken rename, but it seemed like a good refactor even though the class ultimately wasn't used in this PR.

**Comment by crobinso** [comment]
Thanks! I made some changes and pushed:

- patch #1 was busted, had to fix some left over references to token_cache.token
- tweaked commit message of commit #2 
- commit #3 needed to s/if/elif/ in one spot
- extended the bugzillarc parsing test case to check the api_key addition

**Comment by djmitche** [comment]
Thanks for the fixes!

**Comment by djmitche** [comment]
Any chance we could see a v2.1.0?

**Comment by crobinso** [comment]
Working on it this week

**Comment by crobinso** [comment]
@djmitche Release out now

**Pull request closed without merging**
