### PR TITLE
Fix API key leak

### PR DESCRIPTION
**Pull request by ricardobranco777**
Fix for https://github.com/python-bugzilla/python-bugzilla/issues/187

```
$ pytest --ro-functional
...
============================================================================== 114 passed in 128.24s (0:02:08) ===============================================================================
```

### CODE REVIEW

**Comment by juliogonzalez** [comment]
For the record...

With `test.py` being:
```
import os
import logging
from bugzilla import Bugzilla
from bugzilla.exceptions import BugzillaError
from requests.exceptions import RequestException

URL = os.getenv("URL", "https://bugzilla.suse.coma")
USER = os.getenv("USER", "test")
API_KEY = "MYAPIKEY"

try:
    client = Bugzilla(URL, force_rest=True, user=USER, api_key=API_KEY)
except (BugzillaError, RequestException) as exc:
    error = exc
    logging.error("%s", exc)
```
(`bugzilla.suse.coma` does not exist)

# Before
```
$ python3 test.py 
ERROR:root:HTTPSConnectionPool(host='bugzilla.suse.coma', port=443): Max retries exceeded with url: /rest/version?Bugzilla_api_key=MYAPIKEY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f54f87912b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

# After
```
python3 test.py 
ERROR:root:HTTPSConnectionPool(host='bugzilla.suse.coma', port=443): Max retries exceeded with url: /rest/version?Bugzilla_api_key= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f395ab9a8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by ricardobranco777** [comment]
Patch included in openSUSE's python-bugzilla:

https://build.opensuse.org/package/view_file/devel:languages:python/python-bugzilla/188-fix-api-key-leak.diff?expand=1

**Comment by crazyscientist** [comment]
@ricardobranco777 Thank you, the changes look good to me :+1: Would you care to add a tiny unittest, too?

**Comment by crazyscientist** [comment]
@crobinso: For the record, `pylint` does not complain, either:

```
$ ./setup.py pylint
running pylint
running pycodestyle
running pylint

**Review by crobinso — APPROVED** [review]

**Comment by crobinso** [comment]
Thank you for reporting + fixing this!

**Comment by ricardobranco777** [comment]
This fix didn't make it to the last release.

**Comment by crobinso** [comment]
@ricardobranco777 there hasn't been a release since this code was committed. (release coming soon hopefully)

However .git currently regressed here due to other changes that happened in the mean time. I sent a PR to fix this again (and add test coverage to be sure) https://github.com/python-bugzilla/python-bugzilla/pull/203

**Pull request merged**
