### PR TITLE
Add some support for bugzilla groups

### PR DESCRIPTION
**Pull request by pypingou**
With this commit one can now search/retrieve a specific group and its
members.
It also stores the list of emails of its members for convenience.

Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

### CODE REVIEW

**Comment by pypingou** [comment]
Note: I have tested this against Red Hat's bugzilla which is a 5.0 instance, I do not know how it performs against older releases.

**Comment by crobinso** [comment]
Thanks for the patches. Upstream I'm in the process of reworking internals a bunch on to support bugzilla REST API. Once that's settled I'll rebase your patches

**Comment by pypingou** [comment]
Do you have any idea of an ETA for the new code?
Having supports for groups may become quite handy in the coming couple of months for the Fedora infra (as we are migrating away from FAS).

**Comment by crobinso** [comment]
I've your patch now, with some changes;

* _getusers 'ids' param is never used, so I removed it
* the group get API doesn't seem to support 'match' value, so I removed it, which removed searchgroups() API too. If you need that, please send a follow up patch to discuss. I assume it was just copied over from the similar searchusers API. bugzilla API docs are here: https://bugzilla.readthedocs.io/en/latest/api/core/v1/group.html#get-group

Please test the changes and make sure they work for your needs

**Comment by pypingou** [comment]
Many thanks for all this, I'll check that it does what we need and come back to you if needed :)

**Pull request closed without merging**
