### PR TITLE
Fallback on author when creator is missing

### PR DESCRIPTION
**Pull request by btlogy**
See #56 for more info

### CODE REVIEW

**Comment by crobinso** [comment]
Thanks for the bug report and patch. According to the bugzilla docs, 'creator' should always be available, so I think this is an rhbz regression that I'll file a bug for. 'author' is the old name that is only sticking around for back compat until bz 5 is released. But it was the only value that worked for bugzilla < 4.

If you change the code to do bz.get("creator", bz.get("author", "")) it will work around the current issue and also make things potentially work with bz < 4, I'll take that patch. Please add 'Closes: #XX' to the commit message, and flesh out the commit message to explain things more so that it's self contained to understand what's going on. Thank you!

**Comment by crobinso** [comment]
rhbz bug: https://bugzilla.redhat.com/show_bug.cgi?id=1515284

**Comment by btlogy** [comment]
I've made a new commit as requested.
But I don't understand why using bg.get() rather than c.get()?
Will bg.get() not return the creator of the bug rather than the comment?

**Comment by btlogy** [comment]
Good I'm testing:

[13:44:32] DEBUG (base:1211) Calling Bug.search with: {'include_fields': ['comments', 'id'], 'id': ['1433987']}
[13:44:35] DEBUG (base:1227) Query returned 1 bugs
[13:44:35] DEBUG (bug:41) Bug(['comments', 'creation_time', 'id'])
Traceback (most recent call last):
  File "/usr/bin/bugzilla", line 1118, in <module>
    main()
  File "/usr/bin/bugzilla", line 1113, in main
    _format_output(bz, opt, buglist)
  File "/usr/bin/bugzilla", line 703, in _format_output
    print(format_field_re.sub(bug_field, opt.outputformat))
  File "/usr/bin/bugzilla", line 689, in bug_field
    (c['time'], bz.get("creator", bz.get("author", "")), c['text']))
AttributeError: 'RHBugzilla' object has no attribute 'get'

I already knew c.get() was working for me. Pushing a new commit...

**Comment by crobinso** [comment]
My shorthand code suggestion was wrong, I didn't use the correct variable name. I'll push a complete fix to git

**Comment by crobinso** [comment]
In git now, thanks!

**Pull request closed without merging**
