### PR TITLE
Add CI job & patch build on Windows

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
Here you can see the failure from the 1st commit b/c rst2man can't be found:
https://github.com/python-bugzilla/python-bugzilla/pull/135/checks?check_run_id=1219972012

with the latest commit all looks good even on Windows.

@crobinso can you please review.

**Comment by atodorov** [comment]
Replaced with `shutil.which()` but that still seems not to work:
https://github.com/python-bugzilla/python-bugzilla/pull/135/checks?check_run_id=1221797263

**Comment by crobinso** [comment]
Yup I just tried that too. Thanks for the CI additions! I'll take this as is

**Comment by atodorov** [comment]
> Yup I just tried that too. Thanks for the CI additions! I'll take this as is

Many thanks. Do you mind pushing a 3.0.1 version to PyPI ?

**Comment by crobinso** [comment]
Sure I'll do that by the end of the day

**Comment by crobinso** [comment]
Uploaded now

**Pull request merged**
